version: '3.3'

services:
  db:
    container_name: wp-${PROJECT_NAME}-db
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - "33060:3306"
    
    env_file: .env

  wordpress:
    container_name: wp-${PROJECT_NAME}-web
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    
    environment:
       WORDPRESS_DB_HOST: "db:3306"
    env_file: .env

  phpmyadmin:
    container_name: wp-${PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - /sessions
    env_file: .env

volumes:
    db_data:
